from collections.abc import Sequence
from datetime import datetime
from typing import Protocol
from uuid import UUID

from controlplane.domain.monitoring_automation import (
    DatasetPublishedEvent,
    MonitoringExecution,
    MonitoringRule,
)


class MonitoringAutomationRepository(Protocol):
    def rule(self, project_id: UUID, id: UUID, *, lock: bool = False) -> MonitoringRule | None: ...
    def rules(self, project_id: UUID) -> Sequence[MonitoringRule]: ...
    def add_rule(self, rule: MonitoringRule) -> None: ...
    def update_rule(self, rule: MonitoringRule, expected_revision: int) -> None: ...
    def next_event(self) -> DatasetPublishedEvent | None: ...
    def finish_event(self, id: UUID, now: datetime) -> None: ...
    def add_execution(self, execution: MonitoringExecution) -> None: ...
    def update_execution(self, execution: MonitoringExecution) -> None: ...
    def execution(self, rule_id: UUID, dataset_id: UUID) -> MonitoringExecution | None: ...
    def executions(
        self, project_id: UUID, rule_id: UUID, limit: int, offset: int
    ) -> Sequence[MonitoringExecution]: ...
    def next_waiting(self, now: datetime) -> MonitoringExecution | None: ...
