from collections.abc import Sequence
from datetime import datetime
from typing import Protocol
from uuid import UUID

from controlplane.domain.schedules import Schedule, ScheduleExecution, TargetKind


class ScheduleRepository(Protocol):
    def get(
        self, id: UUID, *, lock: bool = False, skip_locked: bool = False
    ) -> Schedule | None: ...
    def add(self, schedule: Schedule) -> None: ...
    def save(self, schedule: Schedule) -> None: ...
    def list(
        self,
        project_ids: Sequence[UUID] | None,
        limit: int,
        offset: int,
        *,
        target_kind: TargetKind | None = None,
        target_name: str | None = None,
        paused: bool | None = None,
    ) -> Sequence[Schedule]: ...
    def due(self, now: datetime, limit: int) -> Sequence[UUID]: ...
    def for_run(self, run_id: UUID, kind: TargetKind) -> ScheduleExecution | None: ...
    def execution(self, id: UUID) -> ScheduleExecution | None: ...
    def occurrence(self, schedule_id: UUID, at: datetime) -> ScheduleExecution | None: ...
    def add_execution(self, execution: ScheduleExecution) -> None: ...
    def save_execution(self, execution: ScheduleExecution) -> None: ...
    def history(
        self, schedule_id: UUID, limit: int, offset: int
    ) -> Sequence[ScheduleExecution]: ...
    def queued(self, limit: int) -> Sequence[ScheduleExecution]: ...
    def coordinate(self, execution: ScheduleExecution) -> bool: ...
    def active(self, execution: ScheduleExecution) -> bool: ...
    def queue_size(self, execution: ScheduleExecution) -> int: ...
    def older_queued(self, execution: ScheduleExecution) -> bool: ...
