"""Transactional dataset publication outbox and monitoring automation."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0030"
down_revision = "0029"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_publication_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id", "project_id"],
            ["dataset_versions.id", "dataset_versions.project_id"],
            name="fk_dataset_event_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id"),
        sa.UniqueConstraint("id", "project_id", name="uq_dataset_event_id_project"),
    )
    op.create_index(
        "ix_dataset_events_pending",
        "dataset_publication_events",
        ["created_at", "id"],
        unique=False,
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.create_index(
        op.f("ix_dataset_publication_events_project_id"),
        "dataset_publication_events",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "monitoring_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("reference_dataset_id", sa.Uuid(), nullable=False),
        sa.Column("observed_dataset_name", sa.String(length=40), nullable=False),
        sa.Column("feedback_dataset_name", sa.String(length=40), nullable=True),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("image", sa.Text(), nullable=False),
        sa.Column("feedback_deadline_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "feedback_deadline_seconds BETWEEN 60 AND 604800",
            name="ck_monitoring_feedback_deadline",
        ),
        sa.CheckConstraint("revision > 0", name="ck_monitoring_rule_revision"),
        sa.ForeignKeyConstraint(
            ["model_id", "project_id"],
            ["models.id", "models.project_id"],
            name="fk_monitoring_rule_model_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id", "model_id"],
            ["model_versions.id", "model_versions.model_id"],
            name="fk_monitoring_rule_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["reference_dataset_id", "project_id"],
            ["dataset_versions.id", "dataset_versions.project_id"],
            name="fk_monitoring_rule_reference",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "project_id", name="uq_monitoring_rule_id_project"),
        sa.UniqueConstraint("project_id", "name", name="uq_monitoring_rule_name"),
    )
    op.create_index(
        op.f("ix_monitoring_rules_project_id"), "monitoring_rules", ["project_id"], unique=False
    )
    op.create_table(
        "monitoring_executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("observed_dataset_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("job_definition_id", sa.Uuid(), nullable=True),
        sa.Column("job_run_id", sa.Uuid(), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'DISPATCHED') = (job_run_id IS NOT NULL AND job_definition_id IS NOT NULL)",
            name="ck_monitoring_execution_dispatched",
        ),
        sa.CheckConstraint(
            "status IN ('WAITING_FEEDBACK', 'DISPATCHED', 'FAILED', 'SKIPPED')",
            name="ck_monitoring_execution_status",
        ),
        sa.ForeignKeyConstraint(
            ["event_id", "project_id"],
            ["dataset_publication_events.id", "dataset_publication_events.project_id"],
            name="fk_monitoring_execution_event",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_definition_id", "project_id"],
            ["job_definitions.id", "job_definitions.project_id"],
            name="fk_monitoring_execution_job",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_run_id", "project_id"],
            ["runs.id", "runs.project_id"],
            name="fk_monitoring_execution_run",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["observed_dataset_id", "project_id"],
            ["dataset_versions.id", "dataset_versions.project_id"],
            name="fk_monitoring_execution_observed",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["rule_id", "project_id"],
            ["monitoring_rules.id", "monitoring_rules.project_id"],
            name="fk_monitoring_execution_rule",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_run_id", name="uq_monitoring_execution_run"),
        sa.UniqueConstraint("rule_id", "observed_dataset_id", name="uq_monitoring_rule_occurrence"),
    )
    op.create_index(
        "ix_monitoring_execution_pending",
        "monitoring_executions",
        ["next_attempt_at", "id"],
        unique=False,
        postgresql_where=sa.text("status = 'WAITING_FEEDBACK'"),
    )
    op.create_index(
        "ix_monitoring_execution_rule_created",
        "monitoring_executions",
        ["rule_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitoring_executions_project_id"),
        "monitoring_executions",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    op.execute("""DO $$ BEGIN
      IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'mlp_api') THEN
        GRANT SELECT, INSERT, UPDATE ON monitoring_rules TO mlp_api;
        GRANT SELECT, INSERT ON dataset_publication_events TO mlp_api;
        GRANT SELECT ON monitoring_executions TO mlp_api;
      END IF;
      IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'mlp_reconciler') THEN
        GRANT SELECT ON monitoring_rules TO mlp_reconciler;
        GRANT SELECT, INSERT, UPDATE ON dataset_publication_events,
          monitoring_executions TO mlp_reconciler;
      END IF;
    END $$""")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_monitoring_executions_project_id"), table_name="monitoring_executions")
    op.drop_index("ix_monitoring_execution_rule_created", table_name="monitoring_executions")
    op.drop_index(
        "ix_monitoring_execution_pending",
        table_name="monitoring_executions",
        postgresql_where=sa.text("status = 'WAITING_FEEDBACK'"),
    )
    op.drop_table("monitoring_executions")
    op.drop_index(op.f("ix_monitoring_rules_project_id"), table_name="monitoring_rules")
    op.drop_table("monitoring_rules")
    op.drop_index(
        op.f("ix_dataset_publication_events_project_id"), table_name="dataset_publication_events"
    )
    op.drop_index(
        "ix_dataset_events_pending",
        table_name="dataset_publication_events",
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.drop_table("dataset_publication_events")
    # ### end Alembic commands ###
