kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ml-platform

nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # inference Service
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      # MLflow tracking server (UI + training from the host)
      - containerPort: 30500
        hostPort: 30500
        protocol: TCP
      # Grafana
      - containerPort: 30300
        hostPort: 30300
        protocol: TCP
  - role: worker
  - role: worker
