"""SQLAlchemy tables for every core entity. Primary keys are UUIDs generated by the
domain; the database never invents identity."""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


def _pk() -> Mapped[UUID]:
    return mapped_column(Uuid, primary_key=True)


def _fk(target: str) -> Mapped[UUID]:
    return mapped_column(Uuid, ForeignKey(target, ondelete="RESTRICT"), nullable=False, index=True)


def _ts() -> Mapped[datetime]:
    return mapped_column(DateTime(timezone=True), nullable=False)


class ProjectRow(Base):
    __tablename__ = "projects"
    __table_args__ = (UniqueConstraint("name", name="uq_projects_name"),)

    id: Mapped[UUID] = _pk()
    name: Mapped[str] = mapped_column(String(40), nullable=False)
    display_name: Mapped[str] = mapped_column(String(120), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    status_reason: Mapped[str | None] = mapped_column(Text)
    traceparent: Mapped[str | None] = mapped_column(String(128))
    created_at: Mapped[datetime] = _ts()
    updated_at: Mapped[datetime] = _ts()


class JobDefinitionRow(Base):
    __tablename__ = "job_definitions"
    __table_args__ = (UniqueConstraint("project_id", "name", name="uq_job_definitions_name"),)

    id: Mapped[UUID] = _pk()
    project_id: Mapped[UUID] = _fk("projects.id")
    name: Mapped[str] = mapped_column(String(40), nullable=False)
    image: Mapped[str] = mapped_column(Text, nullable=False)
    command: Mapped[list[str]] = mapped_column(JSONB, nullable=False)
    resources: Mapped[dict[str, str]] = mapped_column(JSONB, nullable=False)
    env: Mapped[dict[str, str]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = _ts()


class RunRow(Base):
    __tablename__ = "runs"
    __table_args__ = (
        UniqueConstraint("project_id", "idempotency_key", name="uq_runs_idempotency_key"),
        Index("ix_runs_status", "status"),
    )

    id: Mapped[UUID] = _pk()
    project_id: Mapped[UUID] = _fk("projects.id")
    job_definition_id: Mapped[UUID] = _fk("job_definitions.id")
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    status_reason: Mapped[str | None] = mapped_column(Text)
    exit_code: Mapped[int | None] = mapped_column(Integer)
    external_ref: Mapped[str | None] = mapped_column(Text)
    cancel_requested: Mapped[bool] = mapped_column(Boolean, nullable=False)
    retry_of: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("runs.id", ondelete="RESTRICT"), index=True
    )
    idempotency_key: Mapped[str | None] = mapped_column(String(200))
    traceparent: Mapped[str | None] = mapped_column(String(128))
    created_at: Mapped[datetime] = _ts()
    updated_at: Mapped[datetime] = _ts()
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class PipelineDefinitionRow(Base):
    __tablename__ = "pipeline_definitions"
    __table_args__ = (
        UniqueConstraint("project_id", "name", "version", name="uq_pipeline_definitions_version"),
    )

    id: Mapped[UUID] = _pk()
    project_id: Mapped[UUID] = _fk("projects.id")
    name: Mapped[str] = mapped_column(String(40), nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    steps: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = _ts()


class PipelineRunRow(Base):
    __tablename__ = "pipeline_runs"
    __table_args__ = (
        UniqueConstraint("project_id", "idempotency_key", name="uq_pipeline_runs_idempotency_key"),
        Index("ix_pipeline_runs_status", "status"),
    )

    id: Mapped[UUID] = _pk()
    project_id: Mapped[UUID] = _fk("projects.id")
    pipeline_definition_id: Mapped[UUID] = _fk("pipeline_definitions.id")
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    status_reason: Mapped[str | None] = mapped_column(Text)
    external_ref: Mapped[str | None] = mapped_column(Text)
    cancel_requested: Mapped[bool] = mapped_column(Boolean, nullable=False)
    commit_sha: Mapped[str | None] = mapped_column(String(64))
    idempotency_key: Mapped[str | None] = mapped_column(String(200))
    traceparent: Mapped[str | None] = mapped_column(String(128))
    created_at: Mapped[datetime] = _ts()
    updated_at: Mapped[datetime] = _ts()
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class StepRunRow(Base):
    __tablename__ = "step_runs"
    __table_args__ = (UniqueConstraint("pipeline_run_id", "step_name", name="uq_step_runs_step"),)

    id: Mapped[UUID] = _pk()
    pipeline_run_id: Mapped[UUID] = _fk("pipeline_runs.id")
    step_name: Mapped[str] = mapped_column(String(40), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    status_reason: Mapped[str | None] = mapped_column(Text)
    exit_code: Mapped[int | None] = mapped_column(Integer)
    created_at: Mapped[datetime] = _ts()
    updated_at: Mapped[datetime] = _ts()
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class ModelRow(Base):
    __tablename__ = "models"
    __table_args__ = (UniqueConstraint("project_id", "name", name="uq_models_name"),)

    id: Mapped[UUID] = _pk()
    project_id: Mapped[UUID] = _fk("projects.id")
    name: Mapped[str] = mapped_column(String(40), nullable=False)
    thresholds: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    alias_drift: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = _ts()


class ModelVersionRow(Base):
    __tablename__ = "model_versions"
    __table_args__ = (
        UniqueConstraint("model_id", "version", name="uq_model_versions_version"),
        UniqueConstraint("model_id", "external_ref", name="uq_model_versions_external_ref"),
        # At most one CHAMPION per model, enforced by the database, not by hope.
        Index(
            "uq_model_versions_one_champion",
            "model_id",
            unique=True,
            postgresql_where=text("status = 'CHAMPION'"),
        ),
    )

    id: Mapped[UUID] = _pk()
    model_id: Mapped[UUID] = _fk("models.id")
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    external_ref: Mapped[str | None] = mapped_column(String(200))
    source_pipeline_run_id: Mapped[UUID | None] = mapped_column(Uuid)
    created_at: Mapped[datetime] = _ts()
    updated_at: Mapped[datetime] = _ts()


class EvaluationRow(Base):
    __tablename__ = "evaluations"

    id: Mapped[UUID] = _pk()
    model_version_id: Mapped[UUID] = _fk("model_versions.id")
    baseline_version_id: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("model_versions.id", ondelete="RESTRICT"), index=True
    )
    metrics: Mapped[dict[str, float]] = mapped_column(JSONB, nullable=False)
    checks: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    created_at: Mapped[datetime] = _ts()
    updated_at: Mapped[datetime] = _ts()


class PromotionRow(Base):
    __tablename__ = "promotions"

    id: Mapped[UUID] = _pk()
    model_version_id: Mapped[UUID] = _fk("model_versions.id")
    previous_champion_id: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("model_versions.id", ondelete="RESTRICT"), index=True
    )
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    created_at: Mapped[datetime] = _ts()
    updated_at: Mapped[datetime] = _ts()


class DeploymentRow(Base):
    __tablename__ = "deployments"
    __table_args__ = (UniqueConstraint("project_id", "name", name="uq_deployments_name"),)

    id: Mapped[UUID] = _pk()
    project_id: Mapped[UUID] = _fk("projects.id")
    name: Mapped[str] = mapped_column(String(40), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    status_reason: Mapped[str | None] = mapped_column(Text)
    desired_revision: Mapped[int | None] = mapped_column(Integer)
    active_revision: Mapped[int | None] = mapped_column(Integer)
    traceparent: Mapped[str | None] = mapped_column(String(128))
    created_at: Mapped[datetime] = _ts()
    updated_at: Mapped[datetime] = _ts()


class DeploymentRevisionRow(Base):
    __tablename__ = "deployment_revisions"
    __table_args__ = (
        UniqueConstraint("deployment_id", "revision", name="uq_deployment_revisions_revision"),
    )

    id: Mapped[UUID] = _pk()
    deployment_id: Mapped[UUID] = _fk("deployments.id")
    revision: Mapped[int] = mapped_column(Integer, nullable=False)
    model_version_id: Mapped[UUID] = _fk("model_versions.id")
    model_uri: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = _ts()


class RolloutRow(Base):
    __tablename__ = "rollouts"
    __table_args__ = (
        # One rollout in flight per deployment, enforced by the database.
        Index(
            "uq_rollouts_one_active",
            "deployment_id",
            unique=True,
            postgresql_where=text("status IN ('PENDING', 'PROGRESSING')"),
        ),
    )

    id: Mapped[UUID] = _pk()
    deployment_id: Mapped[UUID] = _fk("deployments.id")
    from_revision: Mapped[int] = mapped_column(Integer, nullable=False)
    to_revision: Mapped[int] = mapped_column(Integer, nullable=False)
    model_version_id: Mapped[UUID] = _fk("model_versions.id")
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    status_reason: Mapped[str | None] = mapped_column(Text)
    steps: Mapped[list[int]] = mapped_column(JSONB, nullable=False)
    current_step: Mapped[int] = mapped_column(Integer, nullable=False)
    gate: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    step_started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    abort_requested: Mapped[bool] = mapped_column(Boolean, nullable=False)
    traceparent: Mapped[str | None] = mapped_column(String(128))
    created_at: Mapped[datetime] = _ts()
    updated_at: Mapped[datetime] = _ts()
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class EndpointRow(Base):
    __tablename__ = "endpoints"
    __table_args__ = (UniqueConstraint("project_id", "name", name="uq_endpoints_name"),)

    id: Mapped[UUID] = _pk()
    project_id: Mapped[UUID] = _fk("projects.id")
    deployment_id: Mapped[UUID] = _fk("deployments.id")
    name: Mapped[str] = mapped_column(String(40), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    url: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = _ts()
    updated_at: Mapped[datetime] = _ts()


class AuditEventRow(Base):
    __tablename__ = "audit_events"
    __table_args__ = (Index("ix_audit_events_entity", "entity_type", "entity_id"),)

    id: Mapped[UUID] = _pk()
    occurred_at: Mapped[datetime] = _ts()
    actor: Mapped[str] = mapped_column(String(120), nullable=False)
    action: Mapped[str] = mapped_column(String(80), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(40), nullable=False)
    entity_id: Mapped[UUID] = mapped_column(Uuid, nullable=False)
    # Deliberately not a foreign key: the audit trail must outlive what it describes.
    project_id: Mapped[UUID | None] = mapped_column(Uuid, index=True)
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    # The trace the change was made in: an audit row can be opened as a trace.
    trace_id: Mapped[str | None] = mapped_column(String(32), index=True)
