#!/usr/bin/env bash
# Regenerate constraints/*.txt: the exact versions a clean resolve produces today.
#
#   constraints/inference.txt     what the inference image installs   (pip install .)
#   constraints/controlplane.txt  what the control plane installs     (pip install ".[controlplane]")
#
# Docker and CI install with `-c constraints/<name>.txt`, so the same commit builds the
# same versions on any day. Run this on linux/x86_64 with the Python the images use
# (3.12) — wheels differ per platform — and commit the result when you bump a dependency.
set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON="${PYTHON:-python3.12}"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

lock() {
  local name="$1" spec="$2"
  "$PYTHON" -m venv "$tmp/$name"
  "$tmp/$name/bin/pip" install -q --upgrade pip
  "$tmp/$name/bin/pip" install -q "$spec"
  {
    echo "# Generated by scripts/lock.sh from '$spec' — do not edit by hand."
    echo "# Python $("$tmp/$name/bin/python" -c 'import platform; print(platform.python_version())'), $(uname -sm)."
    "$tmp/$name/bin/pip" freeze --exclude ml-platform-infra | sort -f
  } > "constraints/$name.txt"
  echo "constraints/$name.txt: $(grep -vc '^#' "constraints/$name.txt") pins"
}

lock inference "."
lock controlplane ".[controlplane]"
