#!/usr/bin/env bash
# Resolve the image dependencies for Linux/amd64 from any host, preserving existing pins.
set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MLP_UV="${MLP_UV:-uv}"
MLP_UV_VERSION=0.12.23
if ! command -v "$MLP_UV" >/dev/null || [[ "$("$MLP_UV" --version | awk '{print $2}')" != "$MLP_UV_VERSION" ]]; then
  echo "Install uv==$MLP_UV_VERSION, or set MLP_UV to that executable." >&2
  exit 1
fi
MLP_LOCK_TEMP="$(mktemp -d)"
trap 'rm -rf "$MLP_LOCK_TEMP"' EXIT
lock() {
  local name="$1"
  local options=()
  local input=pyproject.toml
  [[ "$name" == training || "$name" == mlflow || "$name" == serving || "$name" == storage-initializer ]] && input="constraints/$name.in"
  [[ "$name" == controlplane ]] && options+=(--extra controlplane)
  if [[ -f "constraints/$name.txt" && "${MLP_LOCK_UPGRADE:-0}" != 1 ]]; then
    cp "constraints/$name.txt" "$MLP_LOCK_TEMP/$name.previous"
    options+=(--constraint "$MLP_LOCK_TEMP/$name.previous")
  fi
  "$MLP_UV" pip compile "$input" ${options[@]+"${options[@]}"} --python-version 3.12 \
    --python-platform x86_64-unknown-linux-gnu --no-header --no-annotate --quiet \
    --output-file "$MLP_LOCK_TEMP/$name.txt"
  {
    echo "# Generated by scripts/lock.sh with uv $MLP_UV_VERSION; target dependencies resolved."
    echo "# Target: CPython 3.12, Linux x86_64. Do not edit by hand."
    cat "$MLP_LOCK_TEMP/$name.txt"
  } > "constraints/$name.txt"
  echo "Regenerated constraints/$name.txt for Linux/amd64."
}
case "${1:-all}" in
  all) lock inference; lock controlplane; lock training; lock mlflow; lock serving; lock storage-initializer ;;
  inference|controlplane|training|mlflow|serving|storage-initializer) lock "$1" ;;
  *) echo "usage: scripts/lock.sh [all|inference|controlplane|training|mlflow|serving|storage-initializer]" >&2; exit 2 ;;
esac
